aws_region_name = "us-east-1"
bucket_name = "gauritest1"
aws_route53_zone = "dev.devopsinabox.aaic.cc"   
aws_route53_record = "gauri.dev.devopsinabox.aaic.cc"
domain_name = "gauri.dev.devopsinabox.aaic.cc"
website_additional_domains="gauri.dev.devopsinabox.aaic.cc"